<?php 

/*
    GET|HEAD   admin filament.admin.pages.dashboard  …
    GET|HEAD   admin/brands filament.admin.resources.…  
    GET|HEAD   admin/brands/create filament.admin.res…  
    GET|HEAD   admin/brands/{record}/edit filament.ad…  
    GET|HEAD   admin/categories filament.admin.resour…  
    GET|HEAD   admin/categories/create filament.admin…  
    GET|HEAD   admin/categories/{record}/edit filamen…  
    GET|HEAD   admin/ingredients filament.admin.resou…  
    GET|HEAD   admin/ingredients/create filament.admi…  
    GET|HEAD   admin/ingredients/{record}/edit filame…  
    GET|HEAD   admin/login filament.admin.auth.login …  
    POST       admin/logout filament.admin.auth.logou…  
    GET|HEAD   admin/products filament.admin.resource…  
    GET|HEAD   admin/products/create filament.admin.r…  
    GET|HEAD   admin/products/{record}/edit filament.…  
    GET|HEAD   admin/reviews filament.admin.resources…  
    GET|HEAD   admin/reviews/create filament.admin.re…  
    GET|HEAD   admin/reviews/{record}/edit filament.a…
    GET|HEAD   admin/stocks filament.admin.resources.…  
    GET|HEAD   admin/stocks/create filament.admin.res…  
    GET|HEAD   admin/stocks/{record}/edit filament.ad…  
    GET|HEAD   admin/users filament.admin.resources.u…  
    GET|HEAD   admin/users/create filament.admin.reso…  
    GET|HEAD   admin/users/{record}/edit filament.adm…  
    GET|HEAD   filament/exports/{export}/download fil…  

    GET|HEAD   admin/ingredients filament.admin.resou…  
    GET|HEAD   admin/ingredients/create filament.admi…  
    GET|HEAD   admin/ingredients/{record}/edit filame…  
    GET|HEAD   admin/login filament.admin.auth.login …  
    POST       admin/logout filament.admin.auth.logou…  
    GET|HEAD   admin/products filament.admin.resource…  
    GET|HEAD   admin/products/create filament.admin.r…  
    GET|HEAD   admin/products/{record}/edit filament.…  
    GET|HEAD   admin/reviews filament.admin.resources…  
    GET|HEAD   admin/reviews/create filament.admin.re…  
    GET|HEAD   admin/reviews/{record}/edit filament.a…
    GET|HEAD   admin/stocks filament.admin.resources.…  
    GET|HEAD   admin/stocks/create filament.admin.res…  
    GET|HEAD   admin/stocks/{record}/edit filament.ad…  
    GET|HEAD   admin/users filament.admin.resources.u…  
    GET|HEAD   admin/users/create filament.admin.reso…  
    GET|HEAD   admin/users/{record}/edit filament.adm…  
    GET|HEAD   filament/exports/{export}/download fil…  
    GET|HEAD   filament/imports/{import}/failed-rows/download filament.imports.failed-rows.download › Filament\Actions › DownloadImportF…
*/